# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodejs-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-nodejs-app
  template:
    metadata:
      labels:
        app: my-nodejs-app
    spec:
      containers:
      - name: web-server
        # IMPORTANT: Use your own Docker Hub username here
        image: your-dockerhub-username/my-k8s-app:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
spec:
  # NodePort makes the service accessible from your Mac's browser
  type: NodePort 
  selector:
    app: my-nodejs-app
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000